### PR TITLE
First E2E Test case

### LINKED ISSUE #7: SUT containers cannot communicate with each other when they are deployed by the agen
The different SUT containers (webmvc, basket-api, basket-data, etc.) are unable to communicate with each other, causing the system to crash when deployed by Jenkins within the agent. However, when deploying them from the host machine, these containers work seamlessly, enabling all functionalities.

Possible root causes:
1. Container names: When deployed from the agent, the containers have an extra '-1' appended to their names. This results in certain application URLs not functioning correctly.
2. Development compose with localhost URIs: Some URIs specified in the Docker Compose file reference 'localhost,' which can lead to issues because the value of 'localhost' differs between the agent (container IP) and the host (e.g., 156...).

### PR DESCRIPTION
**Pull request by augustocristian**
Added:
- Base Test case with the set-up, tear-down, login and logout methods.
- Navigation utilities
- Browser managers
- Closes #7

### CODE REVIEW

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+
+import java.io.IOException;
+import java.nio.file.Files;
+import java.nio.file.Paths;
+import java.util.Date;
+import java.util.Properties;
+
+import static org.openqa.selenium.logging.LogType.BROWSER;
+
+public class BaseLoggedTest {
```
Comment (javiertuya) [inline src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java:32]: The purpose and/or rationale of this class (and other main classes) should be documented

File: src/test/java/giis/eshopcontainers/e2e/functional/model/EShopUser.java [hunk 2]
```diff
@@ -0,0 +1,33 @@
+package giis.eshopcontainers.e2e.functional.model;
```
Comment (javiertuya) [inline src/test/java/giis/eshopcontainers/e2e/functional/model/EShopUser.java:1]: As we are doing tests, not replicating a domain model. Is there any reason to add a class like this?

File: src/test/resources/inputs/test.properties
Comment (javiertuya) [inline src/test/resources/inputs/test.properties:1]: This file is the test configuration, but it is empty. Also, it should be located at the resources root

File: sut/src/docker-compose.retorch.yml [hunk 3]
```diff
@@ -173,15 +173,15 @@ services:
     volumes:
       - ./ApiGateways/Envoy/config/mobileshopping:/etc/envoy
     ports:
-    - "5200:80"
-    - "15200:8001"
+      - "5200:80"
```
Comment (javiertuya) [inline sut/src/docker-compose.retorch.yml:176]: General: avoid mixing formatting changes and functional changes, specially in large PRs like this. See https://github.com/giis-uniovi/.github/blob/main/profile/CONTRIBUTING.md

File: Jenkinsfile [hunk 4]
```diff
@@ -4,16 +4,23 @@ pipeline {
     }
 
     environment {
-        ET_EUS_API = "http://selenoid:4444/wd/hub"
-        SUT_URL = "$WORKSPACE/sut"
+        SELENOID_URL = "http://selenoid:4444/wd/hub"
+        SUT_LOCATION = "$WORKSPACE/sut"
         E2ESUITE_URL = "$WORKSPACE"
+        IP_SERVER="156.35.119.57"
```
Comment (javiertuya) [inline Jenkinsfile:10]: Do not place hardcoded addresses like this in the jenkinsfile. Use docker network addresing to locate the services.

File: pom.xml [hunk 5]
```diff
@@ -18,6 +18,12 @@
 	<properties>
```
Comment (javiertuya) [inline pom.xml:18]: Reorder definitions (project and maven before dependencies).
Separate each property that is used for dependencies by a blank line to avod conflicts when creating combined updates.

File: pom.xml [hunk 6]
```diff
@@ -18,6 +18,12 @@
...
 		<maven.compiler.source>1.8</maven.compiler.source>
 		<maven.compiler.target>1.8</maven.compiler.target>
+		<junit.jupiter.version>5.5.2</junit.jupiter.version>
+		<junit.platform.version>1.0.0</junit.platform.version>
```
Comment (javiertuya) [inline pom.xml:22]: Check version definitions, as there are definitions that are not used at all.

File: pom.xml [hunk 7]
```diff
@@ -40,6 +46,41 @@
 				<version>2.21.1</version>
 				<scope>test</scope>
 			</dependency>
+			<!--Dependencies Selenium and webdrivers-->
+
+			<dependency>
+				<groupId>io.github.bonigarcia</groupId>
+				<artifactId>selenium-jupiter</artifactId>
```
Comment (javiertuya) [inline pom.xml:53]: If this dependency is not used, remove it

File: pom.xml [hunk 8]
```diff
@@ -40,6 +46,41 @@
...
+				<version>${selenium-jupiter.version}</version>
+				<scope>test</scope>
+			</dependency>
+
+			<dependency>
+				<groupId>org.junit.jupiter</groupId>
+				<artifactId>junit-jupiter-params</artifactId>
```
Comment (javiertuya) [inline pom.xml:60]: Same comment. Remove all unused dependencies

File: src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java [hunk 9]
```diff
@@ -0,0 +1,31 @@
...
+import org.openqa.selenium.By;
+import org.openqa.selenium.WebElement;
+
+class LoggedUserTest extends BaseLoggedTest {
+    @Test
+    @DisplayName("BasicLoginTest")
+    void loginTest() throws InterruptedException, ElementNotFoundException {
+        log.info("Starting test");
+        this.login(user, true);
+
```
Comment (javiertuya) [inline src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java:17]: Use single empty lines to separate blocks, see: https://github.com/giis-uniovi/.github/blob/main/profile/CONTRIBUTING.md

File: src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java [hunk 10]
```diff
@@ -0,0 +1,31 @@
...
+
+        WebElement logged_user = user.getDriver().findElement(By.xpath("//*[@id=\"logoutForm\"]/section[1]/div"));
```
Comment (javiertuya) [inline src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java:19]: Use java naming conventions.

File: src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java [hunk 11]
```diff
@@ -0,0 +1,31 @@
...
+        Assertions.assertEquals("alice", logged_user.getText());
+        WebElement product = user.getDriver().findElement(By.xpath("/html/body/div/div[3]/div[3]/form/input[1]"));
```
Comment (javiertuya) [inline src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java:21]: Xpath locators lead to complex expressions, I assume that you have checked that you can't get a simpler location, right?

Just another tip: Because PageObjects are not used for the tests, over the time you may need shorten the element finding statements, maybe in the superclass

File: src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java [hunk 12]
```diff
@@ -0,0 +1,31 @@
...
+import org.junit.jupiter.api.DisplayName;
+import org.junit.jupiter.api.Test;
+import org.openqa.selenium.By;
+import org.openqa.selenium.WebElement;
+
+class LoggedUserTest extends BaseLoggedTest {
+    @Test
+    @DisplayName("BasicLoginTest")
+    void loginTest() throws InterruptedException, ElementNotFoundException {
+        log.info("Starting test");
```
Comment (javiertuya) [inline src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java:15]: If you need log all start and end of tests, you can move logging to the base class (and include the test name)

**Review by javiertuya — CHANGES_REQUESTED** [review]
I finished the first review. Summary:
- Clarify the design of Driver related classes, as now, it is mixing the responsibilities to manage chrome dependent features and local/remote driver features
- Java/giis styling and naming conventions
- Review the test configuration (driver, browser, sut, users...), use environment variables and properties where appropriate, and remove hardcoded configuration strings.

As this is a large PR that mixes very specific and general issues I would recommend first read all comments, then change the code and finally use the comments as a checklist and mark them as solved. We can meet if necessary.

@ClaudiodelaRiva FYI

**Comment by javiertuya** [comment]
@augustocristian Maybe you have requested review by accident, there are many unresolved comments.

The pom.xml has conflicts because you have changed all lines, Return it back to the previous version and reapply the changes.

**Comment by javiertuya** [comment]
@augustocristian I converted this to a draft to avoid notification spam for every commit you made

File: src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java (hunk 11 above)
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java:18]: > Xpath locators lead to complex expressions, I assume that you have checked that you can't get a simpler location, right?
> 
> Just another tip: Because PageObjects are not used for the tests, over the time you may need shorten the element finding statements, maybe in the superclass

Yes, these elements don't have an ID that allows us to identify them by it. To shorten the reference to the element called, in Fullteaching, we utilize a [Constants](https://github.com/giis-uniovi/retorch-st-fullteaching/blob/main/src/test/java/com/fullteaching/e2e/no_elastest/common/Constants.java) file. This file serves to consolidate and prevent the repetition of IDs, Xpaths, and other attributes across multiple sites.

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java [hunk 13]
```diff
@@ -0,0 +1,181 @@
...
+        } else {
+            SUT_URL = LOCALHOST;
+
+        }
+        CLIENT_BROWSER = System.getenv("CLIENT_BROWSER");
+        if ((CLIENT_BROWSER == null)) {
+            CLIENT_BROWSER = CHROME;
+        }
+
+    }
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java:53]: > I'm not sure whether using environment variables is better approach thatn using a properties file to configure the test. Using environmente variables leads to more code by checking nulls and with defaults hardwritten in the source code instead of externalized in a properties file.

I am utilizing environment variables because in the event of parallel instances of the System Under Test (SUT), such as with four different eShopContainers, various URLs for the webmvc can be dynamically passed through these variables. For instance, the first one could be '[http://webmvc-tjobA:80](http://webmvc-tjoba/)', the second '[http://webmvc-tjobB:80](http://webmvc-tjobb/)', and so on.

[the remark this answers is not in the document]
Comment (javiertuya) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java]: ok, then the approach is use properties that are "global" and using env vars when they are TJob specific, right?

File: src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java (hunk 11 above)
Comment (javiertuya) [reply src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java:18]: IMO using a constants file is the worst option because it loses functional cohesion.

Maybe I didn't explained well, I wanted to say that later (in the future) it could be needed to shorten the expressions that find statements (user.getDriver().findElement()). I didn't mentioned the strings. This is not urgent for now

Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java:18]: All clear! I believe that on Sunday, I accidentally requested a revision because the 'green' button for sending is also used for the review request

File: src/test/java/giis/eshopcontainers/e2e/functional/common/ChromeUser.java [hunk 14]
```diff
@@ -0,0 +1,114 @@
...
+        logPrefs.enable(BROWSER, ALL);
+        options = new ChromeOptions();
+
+        options.setCapability("goog:loggingPrefs", logPrefs);
+
+        //Problems with the max attempt of retry, solved with : https://github.com/aerokube/selenoid/issues/1124 solved with --disable-gpu
+        //Problems with flakiness due to screen resolution solved with --start-maximized
+        String[] arguments = {"--no-sandbox", "--disable-dev-shm-usage", "--allow-elevated-browser", "--disable-gpu", "--start-maximized"};
+
+        log.debug("Adding the arguments ({})", Arrays.toString(arguments));
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/ChromeUser.java:40]: I have adjusted multiple messages to the DEBUG level. As a convention, the log messages at the start and end of various test lifecycle methods (such as @BeforeAll, @Before...) are logged as INFO. Most of the different traces and messages related to debugging, such as setting up browsers and interactions with the UI, are logged as DEBUG. However, some messages remain as info, for example, indicating the type of browser (remote or local) that could be usefull debugging. Is this approach correct?

File: src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java (hunk 11 above)
Comment (javiertuya) [reply src/test/java/giis/eshopcontainers/e2e/functional/LoggedUserTest.java:18]: I'm not sure what this is the reason, because I still receive notifications for every commit (3 commits today), despite I changed the PR to draft, that is the standard procedure to avoid the spam...

File: src/test/java/giis/eshopcontainers/e2e/functional/common/ChromeUser.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (javiertuya) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/ChromeUser.java:40]: Yes, it this is reasonable, is up to you to decide the debug level to avoid to verbose logs that make difficult the debugging.

File: sut/src/docker-compose.retorch.yml (hunk 3 above)
Comment (augustocristian) [reply sut/src/docker-compose.retorch.yml:176]: I apologize; I edited this file to enable networking between the System Under Test (SUT), the slave, and Selenoid. Unfortunately, I had to adjust the indentation in the ports.

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java]: Yes!

File: src/test/java/giis/eshopcontainers/e2e/functional/common/ChromeUser.java [hunk 15]
```diff
@@ -0,0 +1,114 @@
...
+    private static final Logger log= LoggerFactory.getLogger(BaseLoggedTest.class);
+    /**
+     * Configures a Chrome web driver for two different scenarios:
+     * 1. A remote web driver deployed with Selenoid, if the SELENOID_URL environment variable is present,
+     *    with the necessary capabilities to record and store the session.
+     * 2. A local web driver for performing the E2E test case.
+     * @param timeOfWaitInSeconds The timeout to configure the default driver waiter.
+     * @param testName A string containing the test name for video storage.
+     */
+    public ChromeUser(int timeOfWaitInSeconds, String testName,String username) {
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/ChromeUser.java]: I've changed several aspects from the original implementation, now the general aspects and in the parent class and the configurations related to chrome in the Chrome class

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java [hunk 16]
```diff
@@ -0,0 +1,181 @@
...
+     *
+     * @param user The user with its remote Web Driver.
+     * @param slow Set to true for a slower login with a 3-second wait, or false for a faster login.
+     */
+    protected void login(BrowserUser user, boolean slow) throws ElementNotFoundException, InterruptedException {
+        Navigation.toMainMenu(user);
+        user.setOnSession(true);
+        log.info("Logging in user {} with mail '{}'", user.getClientData(), logged_user.getEmail());
+
+        user.waitUntil(ExpectedConditions.elementToBeClickable(By.xpath("//a[contains(text(),'Login')]")), "The button searched by xPath //a[contains(text(),'Login')] is not clickable");
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java]: Separated: button location click, password and user location and click and login button location and click

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java [hunk 17]
```diff
@@ -0,0 +1,181 @@
...
+                + "s.innerText = 'window.MY_FUNC = function(containerQuerySelector) {"
+                + "var elem = document.createElement(\"div\");"
+                + "elem.id = \"video-playing-div\";"
+                + "elem.innerText = \"VIDEO PLAYING\";"
+                + "document.body.appendChild(elem);"
+                + "console.log(\"Video check function successfully added to DOM by Selenium\")}';"
+                + "window.document.head.appendChild(s);";
+        u.runJavascript(GLOBAL_JS_FUNCTION);
+
+        return u;
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java]: Now, the responsibility of instantiating the browser is entirely delegated to the setup method. The setup, annotated with @BeforeAll, now retrieves environment variables and loads properties files that remain unchanged throughout the rest of the tests.

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java [hunk 18]
```diff
@@ -0,0 +1,181 @@
...
+
+        user = setupBrowser(TJOB_NAME, testInfo.getDisplayName(), 1);
+    }
+
+    protected BrowserUser setupBrowser(String tJobName, String testName,
+                                       int secondsOfWait) {
+
+        log.info("Starting browser ({})", "Chrome");
+
+        BrowserUser u = new ChromeUser(secondsOfWait, testName,logged_user.getEmail());
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedTest.java]: Solved all the blank problems

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BrowserUser.java [hunk 19]
```diff
@@ -0,0 +1,68 @@
...
+
+    public void dispose() {
+        this.driver.quit();
+    }
+
+    public Object runJavascript(String script, Object... args) {
+        return ((JavascriptExecutor) this.driver).executeScript(script, args);
+    }
+
+    public boolean isOnSession() {
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BrowserUser.java]: Named 'isLogged,' this variable checks whether the user is still logged in, and if so, logs them out. May be adecuate check if the driver is instantiated?

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BrowserUser.java [hunk 20]
```diff
@@ -0,0 +1,68 @@
...
+
+public class BrowserUser {
+    private static final Logger log= LoggerFactory.getLogger(BaseLoggedTest.class);
+    protected final String clientData;
+    protected final int timeOfWaitInSeconds;
+    protected WebDriver driver;
+    protected boolean isOnSession;
+    protected WebDriverWait waiter;
+
+    public BrowserUser(String clientData, int timeOfWaitInSeconds) {
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BrowserUser.java]: It would be interesting to use this tool, especially since it's maintained/created by you. However, it might be more appropriate to create another pull request for this feature No?

[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BrowserUser.java]: Still working on instantiate the driver with selema @javiertuya. 
The rest of the changes are done.

[the remark this answers is not in the document]
Comment (javiertuya) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BrowserUser.java]: You decide, it was only a suggestion, it was only a suggestion to simplify driver creation

**Comment by augustocristian** [comment]
@javiertuya  All the browsers management changed to Selema, ready for review

File: src/test/resources/inputs/test.properties
Comment (javiertuya) [reply src/test/resources/inputs/test.properties:1]: Now it is not empty, right, but should be placed at the resources root

File: pom.xml (hunk 6 above)
Comment (javiertuya) [reply pom.xml]: Recheck version definitions, some of them still have not a dependency.

**Review by javiertuya — CHANGES_REQUESTED** [review]
Now everything is much clearer, only a few things to revise.
- Ensure that all conversations are marked as resolved before requesting review, unless some discussion is needed. Note that some unresolved conversations from the first review may appear as hidden in the GitHub UI
- Test in local to avoid overloading the CI (this will be more important when you have a larger set of tests)
- Do not force push the commits during revision
- Keep this PR in draft state when requessting review, I have to check if force pushes are the cause of the notification spam.

@ClaudiodelaRiva FYI

File: pom.xml [hunk 21]
```diff
@@ -18,30 +18,64 @@
...
+				<version>${slf4j-api.version}</version>
 			</dependency>
 			<dependency>
 				<groupId>org.apache.logging.log4j</groupId>
 				<artifactId>log4j-slf4j2-impl</artifactId>
-				<version>2.21.1</version>
+				<version>${log4j-slf4j2-impl.version}</version>
 				<scope>test</scope>
 			</dependency>
+			<!--	As of version 4, Selenium-Jupiter does not include Selenium WebDriver as a transitive dependency.-->
```
Comment (javiertuya) [inline pom.xml:61]: Remove comment

File: retorchfiles/scripts/testexecution.sh [hunk 22]
```diff
@@ -1,8 +1,5 @@
 #!/bin/bash
 #https://stackoverflow.com/questions/4365418/get-state-of-maven-execution-within-shell-script
 $E2ESUITE_URL/retorchfiles/scripts/writetime.sh "$2" "$1" #$2 is the stage, $1 tjob
-echo 'Starting 10 seconds sleep'
-sleep 10
-echo 'End 10 seconds sleep'
-mvn test
+mvn test -DSUT_URL="156.35.119.57" -DSUT_PORT=5100 -Ddirtarget=TJOBExample -Dtjob_name=tjobe
```
[the remark this answers is not in the document]
Comment (augustocristian) [reply retorchfiles/scripts/testexecution.sh:4]: @javiertuya  What is the most convenient way to store the server URL? one Jenkins credential? Create an env variable in the slave dockerfile?

[the remark this answers is not in the document]
Comment (javiertuya) [reply retorchfiles/scripts/testexecution.sh]: - Jenkins credential: this would require some jenkins configuration, but this should be independent from the agent, I would discard this
- Environment variable in the agent: right, it is similar to other configurations you made, where you use an env var that fallbacks to localhost when running running in local
- Another option: use docker addressing, if the SUT network is added to the jenkins agent

[the remark this answers is not in the document]
Comment (augustocristian) [reply retorchfiles/scripts/testexecution.sh]: The issue has been addressed in the latest commit. I am employing Docker local networks, which are polled to the various containers by the slave, along with binded ports. This enables us to deploy multiple System Under Tests (SUTs) in the future. Instead of relying on container names, which caused issues due to their diverse origins as demonstrated in #13, we now utilize a pool of ports that will be distributed among the various scenarios.

**Comment by augustocristian** [comment]
The pull request is ready for another review. I apologize for the force pushes I made yesterday; I mistakenly worked on the wrong branch and updated the incorrect ones. As a result, I had to undo all the changes. The last two commits address the addressing problems and incorporate the final requested changes

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedClass.java [hunk 23]
```diff
@@ -0,0 +1,148 @@
...
+
+        log.debug("Finishing set-up browser ({})", properties.getProperty("BROWSER_USER"));
+    }
+
+    /**
+     * Navigates to the main menu to enter a user session.
+     */
+    protected void login() throws ElementNotFoundException {
+        Navigation.toMainMenu(driver, waiter);
+        isLogged = true;
```
[the remark this answers is not in the document]
Comment (javiertuya) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedClass.java:96]: Not yet fixed

**Review by javiertuya — CHANGES_REQUESTED** [review]
Just one unresolved comment

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedClass.java (hunk 23 above)
[the remark this answers is not in the document]
Comment (augustocristian) [reply src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedClass.java]: I dont know why but I pushed this changes one hour ago, now its fixed

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedClass.java [hunk 24]
```diff
@@ -92,22 +92,28 @@ protected static void setupBrowser() {
...
-        WebElement userNameField = driver.findElement(By.id("Username"));
-        waiter.waitUntil(ExpectedConditions.presenceOfElementLocated(By.id("Password")), "The Password login is not present");
-        WebElement userPassField = driver.findElement(By.id("Password"));
-        userNameField.sendKeys(userName);
-        userPassField.sendKeys(password);
-
-        waiter.waitUntil(ExpectedConditions.elementToBeClickable(By.xpath("//button[contains(.,'Login')]")), "The button searched by xpath //button[contains(.,'Login')] is not clickable");
-        Click.element(driver, waiter, driver.findElement(By.xpath("//button[contains(.,'Login')]")));
-        log.debug("Logging in successful for user {}", userName);
+        try {
```
Comment (javiertuya) [inline src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedClass.java:95]: Do not catch exceptions in tests, let junit catch exceptions for you. Revert this change.

File: src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedClass.java [hunk 25]
```diff
@@ -92,22 +92,28 @@ protected static void setupBrowser() {
...
+            Navigation.toMainMenu(driver, waiter);
+            isLogged = true;
```
Comment (javiertuya) [inline src/test/java/giis/eshopcontainers/e2e/functional/common/BaseLoggedClass.java:97]: The original comment 
https://github.com/giis-uniovi/retorch-st-eShopContainers/pull/6/files/125da58fbcb3cf72f80718dc6e5e09ec2b7bf9ce#r1397599638
said "If the login is not successful, the test teardown will try to logout and will fail"

This is because you set isLogged true BEFORE trying the login. You should set it to true AFTER login, so that if login fails, the test fails and then the teardown is executed with isLogged false as desired (do not try logout)

**Review by javiertuya — CHANGES_REQUESTED** [review]
Check latest change. Do not catch exceptions inside tests, this is what junit runner does

**Review by javiertuya — APPROVED** [review]
Take into account for next PR (again):
- Do not force push while in revision
- Do not mix formatting and functional changes in the same PR

**Comment by javiertuya** [comment]
@augustocristian PR is complete, but can't be merged because of conflicts

**Comment by javiertuya** [comment]
Conflicts have dissapeared from the PR UI, merging
